---
title: "ESM229_PS1"
author: "Camila Bobroff"
date: "1/14/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(dplyr)
```


# ESM 229: Economics and policy of climate change
# Problem Set 1
# This script builds a toy IAM model with no abatement and welfare. Based loosely on David Anthoff's assignments
# Author: Kyle Meng
# Date: 10/7/14. Updated: 10/1/15.
```{r}
###################### Part 0: Program file directory, initial conditions, parameters ###################### 

####### Part 0a: Set file directory, clear workspace ######

    # #set your own directory here 
    # setwd('~/Documents/Dropbox/work/teaching/UCSB/2016_2017/ESM_229/problem_sets/Problem_set1')
    # rm(list=ls()) # clears workspace

#######  Part 0b: Model parameters ###### 

    # Fixed Economic parameters (LEAVE THIS ALONE FOR NOW)
    p_saving<-c(.22) # output saved, default at 0.22
    p_capShare<-c(.3) # Cobb-Douglas capital share, defaut at 0.3
    p_capDep<-c(.1) # capital depreciation, default at 0.1
    p_TFP_g<-(.005) # TFP (total factor productivity) growth rate, default at 0.005
    p_damage<-c(.009) # default at 0.009

    # Variable Economic parameters (TRY DIFFERENT VALUES)
    p_emInt_g<-c(-.005) # default at -.005 (emissions intensity)
    p_enInt_g<-c(-.01) # default at -.01 (energy intensity)
    p_pop_g<-c(.01) # default at .01
    
    # Fixed climate parameters (LEAVE THIS ALONE)
    p_carDecay<-400 # carbon decay, default 400
    p_climDelay<-c(.015) # climate decay, default 0.015

    #Variable climate parameters (TRY DIFFERENT VALUES)
    p_climSens<-c(2.5) # climate sensitivity default 2.5

###### Part 0c: Initial conditions (in 2010) ###### 
    
    # years
    p_years<-c(291)

    # Economic
    ic_pop<-c(6900) # in millions
    ic_enInt<-c(5.98) # in EJ/$trill
    ic_emInt<-c(68.27) # in Mt CO2 /EJ            
    ic_K<-c(139.65) # $trill   
    ic_TFP<-c(.03)

    # Climate
    ic_preCO2<-c(275) # ppm
    ic_nowCO2<-c(380) # ppm
    ic_T<-c(0.8) # degree C above preindustrial

    # creating empty matrices for storing data
    year<-matrix(0,p_years,1)    
    pop<-matrix(0, p_years,1)
    enInt<-matrix(0, p_years,1)
    emInt<-matrix(0, p_years,1)    
    TFP<-matrix(0, p_years,1)
    Y_gross<-matrix(0, p_years,1)
    K<-matrix(0, p_years,1)
    gdppc<-matrix(0, p_years,1)
    CO2ppm<-matrix(0, p_years,1)
    em_MtCO2<-matrix(0,p_years,1)
    em_ppm<-matrix(0,p_years,1)
    Y_net<-matrix(0,p_years,1)
    C<-matrix(0,p_years,1)
    C_pc<-matrix(0,p_years,1)
    Teq<-matrix(0,p_years,1)
    climateDamage<-matrix(0,p_years,1)

############################ Part 1: economic model ################################## 
####### Part 1a: Getting exogenous changes in population, energy intensity, emissions intensity, TFP####### 

    # initializing for first period    
    year[1]<-2010
    pop[1]<-ic_pop
    enInt[1]<-ic_enInt    
    emInt[1]<-ic_emInt
    TFP[1]<-ic_TFP

    for (j in 2:p_years) {
      year[j]<-year[j-1]+1
      pop[j]=pop[j-1]*(1+p_pop_g)
      enInt[j]=enInt[j-1]*(1+p_enInt_g)
      emInt[j]=emInt[j-1]*(1+p_emInt_g)
      TFP[j]=TFP[j-1]*(1+p_TFP_g)
    }

######## Part 1b: Getting gross output, capital, emissions ############## 

    # initializing for first period
    #Part 1: Economic model w/o climate damages
    K[1]<-ic_K
    Y_gross[1]<-TFP[1]*K[1]^p_capShare*pop[1]^(1-p_capShare)
      
    #Part 2: climate model
    #CO2 concentration
    CO2ppm[1]<-ic_nowCO2                      
    T[1]=ic_T

    #Part 3: Economic model with climate damages
    #climate damages
    climateShare<-(p_damage*T[1]^2)/(1+p_damage*T[1]^2) # damage function
    climateDamage[1]<-climateShare*Y_gross[1] #climate damages
    Y_net[1]<-Y_gross[1]-climateDamage[1] # net of damages output          
    C[1]<-Y_net[1]-p_saving*Y_net[1]
    C_pc[1]<-(C[1]/pop[1])*1000
    
    # looping over rest of the years
    for (j in 2:p_years) {
      
      #Part 1: Economic model w/o climate damages     
      #Economic output 
      K[j]<-(1-p_capDep)*K[j-1]+p_saving*Y_net[j-1]  #capital accumulation
      Y_gross[j]<-TFP[j]*K[j]^p_capShare*pop[j]^(1-p_capShare) #Cobb-Douglas production function
      gdppc[j]=Y_gross[j]/pop[j]

      #emissions
      em_MtCO2[j]<-pop[j]*gdppc[j]*enInt[j]*emInt[j] #Kaya identity
      em_ppm[j]<-em_MtCO2[j]/7810 # convert to atmospheric CO2 concentrations
      
      #Part 2: climate model     
      #CO2 concentration
      CO2ppm[j]<-CO2ppm[j-1]+0.5*((em_ppm[j])- (CO2ppm[j-1]-(ic_preCO2))/(p_carDecay)) #CO2 concentration accumulation                             
    
      #Radiative forcing
      rad_CO2_Wpm2<-5.35*log(CO2ppm[j]/ic_preCO2)

      # Converting to temperature  
      Teq[j]<-rad_CO2_Wpm2*(p_climSens/(5.3*log(2))) #Equilibrium temperature
      T[j]=T[j-1]+p_climDelay*(Teq[j]-T[j-1]) #Transient temperature

      #Part 3: Economic model with climate damages
      climateShare<-(p_damage*T[j]^2)/(1+p_damage*T[j]^2) # damage function
      climateDamage[j]<-climateShare*Y_gross[j] # climate damages
      Y_net[j]<-Y_gross[j]-climateDamage[j] # output net of damages          
      C[j]<-Y_net[j]-p_saving*Y_net[j] # consumption 
      C_pc[j]<-(C[j]/pop[j])*1000 #per capita consumption     
    }
  


###################### Part 4: plots ###################### 

par(mfrow=c(3,2), mar=c(4,4,2,2))
plot(year[2:j], em_MtCO2[2:j], ylab="Emissions (MtCO2)", xlab="Year")
plot(year[2:j], CO2ppm[2:j], ylab="CO2 concentrations (ppm)")
plot(year[2:j], T[2:j], ylab="Transient temperature (C)")
plot(year[2:j], Teq[2:j], ylab="Equilibrium temperature (C)")
plot(year[2:j], Y_net[2:j], ylab="Net output ($ trillion)")
plot(year[2:j], C_pc[2:j], ylab="Consumption per cap ($ thousand)")
```

Problem Set Answers

Part 1. 
```{r}
# BAU benchmark with default growth rate
plot(year[2:j], em_MtCO2[2:j], ylab = "Emissions (MtCO2)", xlab = "Year", main = "BAU Scenario with Default Growth Rate (.005)")

# No change in population, default rates for all else
# Changed: p_pop_g<-c(0) (default was at .01)
plot(year[2:j], em_MtCO2[2:j], ylab = "Emissions (MtCO2)", xlab = "Year", main = "No Change in Population")

# No change in emissions intensity, default rates for all else
# Changed: p_pop_g<-c(0) (default was at .01)
plot(year[2:j], em_MtCO2[2:j], ylab = "Emissions (MtCO2)", xlab = "Year", main = "No Change in Emissions Intensity")

# No change in energy intensity, default rates for all else
# Changed: p_pop_g<-c(0) (default was at .01)
plot(year[2:j], em_MtCO2[2:j], ylab = "Emissions (MtCO2)", xlab = "Year", main = "No Change in Energy Intensity")

```

Part 2.
```{r}
#Hold pop and energy intensity at default, what is the maximum rate for change in emissions intensity such that equilibrium temperature does not exceed 2°C?
#Answer after guess and check: p_emInt_g<-c(-.017) # default at -.005 (emissions intensity)
plot(year[2:j], Teq[2:j], ylab="Equilibrium temperature (C)", xlab = "Year", main = "Maximum Rate of Emissions Intensity to Stay Below 2°C (-0.017)")

#Hold pop and emissions intensity at default, what is the maximum rate for change in energy intensity such that equilibrium temperature does not exceed 2°C?
#Answer after guess and check: p_enInt_g<-c(-.022) # default at -.01 (energy intensity)
plot(year[2:j], Teq[2:j], ylab="Equilibrium temperature (C)", xlab = "Year", main = "Maximum Rate of Energy Intensity to Stay Below 2°C (-0.022)")

#Replicate both exercises for when the equilibrium climate sensitivity parameters (ECS), called p_climSen in the model, is set to the IPCC AR5 lower and upper bounds of 1.5°C and 4.5°C. What are the necessary energy and emissions intensity rates so that equilibrium temperatures never exceed 2°C for the ECS lower and upper bounds? Does this look achievable?

#Lower bound: 1.5°C
#Answer after guess and check: p_emInt_g<-c(-.008) # default at -.005 (emissions intensity)
plot(year[2:j], Teq[2:j], ylab="Equilibrium temperature (C)", xlab = "Year", main = "Max Rate of Emissions Intensity to Stay Below 2°C (ECS1.5°C,-0.008)")
#Answer after guess and check: p_enInt_g<-c(-.013) # default at -.01 (energy intensity)
plot(year[2:j], Teq[2:j], ylab="Equilibrium temperature (C)", xlab = "Year", main = "Max Rate of Energy Intensity to Stay Below 2°C (ECS1.5°C,-0.013)")

#Upper bound: 4.5°C
#Not feasible, even at most extreme ratio (-1)
plot(year[2:j], Teq[2:j], ylab="Equilibrium temperature (C)", xlab = "Year", main = "Infeasible to Stay Below 2°C (ECS4.5°C,emInt-1)")
#Not feasible, even at most extreme ratio (-1)
plot(year[2:j], Teq[2:j], ylab="Equilibrium temperature (C)", xlab = "Year", main = "Infeasible to Stay Below 2°C (ECS1.5°C,enInt-1)")
```

Part 3.

```{r}
###################### Part 0: Program file directory, initial conditions, parameters ###################### 

####### Part 0a: Set file directory, clear workspace ######

    # #set your own directory here 
    # setwd('~/Documents/Dropbox/work/teaching/UCSB/2016_2017/ESM_229/problem_sets/Problem_set1')
    # rm(list=ls()) # clears workspace

#######  Part 0b: Model parameters ###### 

    # Fixed Economic parameters (LEAVE THIS ALONE FOR NOW)
    p_saving<-c(.22) # output saved, default at 0.22
    p_capShare<-c(.3) # Cobb-Douglas capital share, defaut at 0.3
    p_capDep<-c(.1) # capital depreciation, default at 0.1
    p_TFP_g<-(.005) # TFP (total factor productivity) growth rate, default at 0.005
    p_damage<-c(.009) # default at 0.009

    # Variable Economic parameters (TRY DIFFERENT VALUES)
    p_emInt_g<-c(-.005) # default at -.005 (emissions intensity)
    p_enInt_g<-c(-.01) # default at -.01 (energy intensity)
    p_pop_g<-c(.01) # default at .01
    
    # Fixed climate parameters (LEAVE THIS ALONE)
    p_carDecay<-400 # carbon decay, default 400
    p_climDelay<-c(.015) # climate decay, default 0.015

    #Variable climate parameters (TRY DIFFERENT VALUES)
    p_climSens<-c(2.5) # climate sensitivity default 2.5

###### Part 0c: Initial conditions (in 2010) ###### 
    
    # years
    p_years<-c(291)

    # Economic
    ic_pop<-c(6900) # in millions
    ic_enInt<-c(5.98) # in EJ/$trill
    ic_emInt<-c(68.27) # in Mt CO2 /EJ            
    ic_K<-c(139.65) # $trill   
    ic_TFP<-c(.03)

    # Climate
    ic_preCO2<-c(275) # ppm
    ic_nowCO2<-c(380) # ppm
    ic_T<-c(0.8) # degree C above preindustrial

    # creating empty matrices for storing data
    year<-matrix(0,p_years,1)    
    pop<-matrix(0, p_years,1)
    enInt<-matrix(0, p_years,1)
    emInt<-matrix(0, p_years,1)    
    TFP<-matrix(0, p_years,1)
    Y_gross<-matrix(0, p_years,1)
    K<-matrix(0, p_years,1)
    gdppc<-matrix(0, p_years,1)
    CO2ppm<-matrix(0, p_years,1)
    em_MtCO2<-matrix(0,p_years,1)
    em_ppm<-matrix(0,p_years,1)
    Y_net<-matrix(0,p_years,1)
    C<-matrix(0,p_years,1)
    C_pc<-matrix(0,p_years,1)
    Teq<-matrix(0,p_years,1)
    climateDamage2<-matrix(0,p_years,1)

############################ Part 1: economic model ################################## 
####### Part 1a: Getting exogenous changes in population, energy intensity, emissions intensity, TFP####### 


    # initializing for first period    
    year[1]<-2010
    pop[1]<-ic_pop
    enInt[1]<-ic_enInt    
    emInt[1]<-ic_emInt
    TFP[1]<-ic_TFP
    
    for (j in 2:p_years) {
      year[j]<-year[j-1]+1
      pop[j]=pop[j-1]*(1+p_pop_g)
      enInt[j]=enInt[j-1]*(1+p_enInt_g)
      emInt[j]=emInt[j-1]*(1+p_emInt_g)
      TFP[j]=TFP[j-1]*(1+p_TFP_g)
    }


######## Part 1b: Getting gross output, capital, emissions ############## 

    # initializing for first period
    #Part 1: Economic model w/o climate damages
    K[1]<-ic_K
    Y_gross[1]<-TFP[1]*K[1]^p_capShare*pop[1]^(1-p_capShare)
      
    #Part 2: climate model
    #CO2 concentration
    CO2ppm[1]<-ic_nowCO2                      
    T[1]=ic_T

    #Part 3: Economic model with climate damages
    #climate damages
    climateShare2<-(p_damage*T[1]^2)/(1+p_damage*T[1]^2) # damage function
    climateDamage2[1]<-climateShare2*Y_gross[1] #climate damages
    Y_net[1]<-Y_gross[1]-climateDamage2[1] # net of damages output          
    C[1]<-Y_net[1]-p_saving*Y_net[1]
    C_pc[1]<-(C[1]/pop[1])*1000
  
    #ADD 1/1000000 to emInt year 2
      emInt[2, ]<-c(67.928651)

    # looping over rest of the years
    for (j in 2:p_years) {
      
      #Part 1: Economic model w/o climate damages     
      #Economic output 
      K[j]<-(1-p_capDep)*K[j-1]+p_saving*Y_net[j-1]  #capital accumulation
      Y_gross[j]<-TFP[j]*K[j]^p_capShare*pop[j]^(1-p_capShare) #Cobb-Douglas production function
      gdppc[j]=Y_gross[j]/pop[j]
      
      #emissions
      em_MtCO2[j]<-pop[j]*gdppc[j]*enInt[j]*emInt[j] #Kaya identity + Social Cost of Carbon
      em_ppm[j]<-em_MtCO2[j]/7810 # convert to atmospheric CO2 concentrations
      
      #Part 2: climate model     
      #CO2 concentration
      CO2ppm[j]<-CO2ppm[j-1]+0.5*((em_ppm[j])- (CO2ppm[j-1]-(ic_preCO2))/(p_carDecay)) #CO2 concentration accumulation                             
    
      #Radiative forcing
      rad_CO2_Wpm2<-5.35*log(CO2ppm[j]/ic_preCO2)

      # Converting to temperature  
      Teq[j]<-rad_CO2_Wpm2*(p_climSens/(5.3*log(2))) #Equilibrium temperature
      T[j]=T[j-1]+p_climDelay*(Teq[j]-T[j-1]) #Transient temperature

      #Part 3: Economic model with climate damages
      climateShare2<-(p_damage*T[j]^2)/(1+p_damage*T[j]^2) # damage function
      climateDamage2[j]<-climateShare2*Y_gross[j] # climate damages
      Y_net[j]<-Y_gross[j]-climateDamage2[j] # output net of damages          
      C[j]<-Y_net[j]-p_saving*Y_net[j] # consumption 
      C_pc[j]<-(C[j]/pop[j])*1000 #per capita consumption     
    }
  


###################### Part 4: plots ###################### 

par(mfrow=c(3,2), mar=c(4,4,2,2))
plot(year[2:j], em_MtCO2[2:j], ylab="Emissions (MtCO2)", xlab="Year")
plot(year[2:j], CO2ppm[2:j], ylab="CO2 concentrations (ppm)")
plot(year[2:j], T[2:j], ylab="Transient temperature (C)")
plot(year[2:j], Teq[2:j], ylab="Equilibrium temperature (C)")
plot(year[2:j], Y_net[2:j], ylab="Net output ($ trillion)")
plot(year[2:j], C_pc[2:j], ylab="Consumption per cap ($ thousand)")
```

```{r}

climateDamageBAU <- climateDamage
climateShareBAU <- climateShare
# 0.1044
climateDamageBAU <- as.data.frame(t(climateDamageBAU)) %>% 
  gather()

climateDamageBAU <- tibble::rowid_to_column(climateDamageBAU, "ID") 

climateDamageBAU_clean <- climateDamageBAU %>%  
  select(ID, value)
names(climateDamageBAU_clean) <- c("year", "climate_damage")


climateDamage2 <- climateDamage2
climateShare2 <- climateShare2
# 
climateDamage2 <- as.data.frame(t(climateDamage2)) %>% 
  gather()

climateDamage2 <- tibble::rowid_to_column(climateDamage2, "year") 

climateDamage2_clean <- climateDamage2 %>%  
  select(year, value)
names(climateDamage2_clean) <- c("year", "climate_damage")

climateDamage_diff <- merge(climateDamageBAU_clean, climateDamage2_clean, by = "year") %>% 
  mutate(diff = climate_damage.y - climate_damage.x)

# Discount Factor (1.5%)
r <- c(.015)

climateDamage_diff_DF <- climateDamage_diff %>%
  mutate(climateDamage_DF = diff*(1/((1+r)^year)))

SCC_1 <- sum(climateDamage_diff_DF$climateDamage_DF)
#9.5955 x10-8 (trillions of dollars)
SCC_1 <- SCC_1*1000000000000
# 95,955

# Discount Factor (3%)
r2 <- c(.03)

climateDamage_diff_DF2 <- climateDamage_diff %>% 
  mutate(climateDamage_DF = diff*(1/((1+r2)^year)))

SCC_2 <- sum(climateDamage_diff_DF2$climateDamage_DF)
#1.1548 x10-8
SCC_2 <- SCC_2*1000000000000
#11,548

```


